### ISSUE TITLE
Panic when start server

### ISSUE THREAD

**Issue by xieydd** [tensorchord/openmodelz#152]
```
$ mdz server start
🚧 Creating the server...
🚧 Waiting for the server to be created...
Failed to start the server: exit status 28
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8c9119]

goroutine 1 [running]:
github.com/tensorchord/openmodelz/mdz/pkg/telemetry.(*defaultTelemetry).Record(0x4072fea35ecb6772?, {0xd5f0cf?, 0x1c36880?}, {0xc000527ae0?, 0xc000012020?, 0xc000527b28?})
	/home/runner/work/openmodelz/openmodelz/mdz/pkg/telemetry/telemetry.go:149 +0x39
github.com/tensorchord/openmodelz/mdz/pkg/cmd.commandServerStart.func1({0x1c21540?, 0xc266a0?, 0x1c36880?})
	/home/runner/work/openmodelz/openmodelz/mdz/pkg/cmd/server_start.go:65 +0x105
github.com/tensorchord/openmodelz/mdz/pkg/cmd.commandServerStart(0x1c21540?, {0x1c67b28?, 0x0, 0x0})
	/home/runner/work/openmodelz/openmodelz/mdz/pkg/cmd/server_start.go:91 +0x6fc
github.com/spf13/cobra.(*Command).execute(0x1c21540, {0x1c67b28, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1c23200)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/tensorchord/openmodelz/mdz/pkg/cmd.Execute()
	/home/runner/work/openmodelz/openmodelz/mdz/pkg/cmd/root.go:48 +0x25
main.main()
	/home/runner/work/openmodelz/openmodelz/mdz/cmd/mdz/main.go:9 +0x17
(mdz)

```

**Comment by kemingy** [comment]
- fixed in https://github.com/tensorchord/openmodelz/pull/146
